// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCELRGa9uZq3b7Oj3nFJQNs6VOc1qDhvMU',
    appId: '1:87825484814:web:af9fea1e1979cf5c51405f',
    messagingSenderId: '87825484814',
    projectId: 'rental-app-bb0ac',
    authDomain: 'rental-app-bb0ac.firebaseapp.com',
    storageBucket: 'rental-app-bb0ac.firebasestorage.app',
    measurementId: 'G-CHGW607VLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq7ad45tqZKiLTghVrruAYsKB1fYjr7Z0',
    appId: '1:87825484814:android:af3ccff2ab80a00b51405f',
    messagingSenderId: '87825484814',
    projectId: 'rental-app-bb0ac',
    storageBucket: 'rental-app-bb0ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4U3Sz6dEmpwt0VfKLzS7vRrnIBx2Cv0Y',
    appId: '1:87825484814:ios:77eba37a2c8e4a4a51405f',
    messagingSenderId: '87825484814',
    projectId: 'rental-app-bb0ac',
    storageBucket: 'rental-app-bb0ac.firebasestorage.app',
    iosBundleId: 'com.example.rentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4U3Sz6dEmpwt0VfKLzS7vRrnIBx2Cv0Y',
    appId: '1:87825484814:ios:77eba37a2c8e4a4a51405f',
    messagingSenderId: '87825484814',
    projectId: 'rental-app-bb0ac',
    storageBucket: 'rental-app-bb0ac.firebasestorage.app',
    iosBundleId: 'com.example.rentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCELRGa9uZq3b7Oj3nFJQNs6VOc1qDhvMU',
    appId: '1:87825484814:web:7640d8f55e182f0551405f',
    messagingSenderId: '87825484814',
    projectId: 'rental-app-bb0ac',
    authDomain: 'rental-app-bb0ac.firebaseapp.com',
    storageBucket: 'rental-app-bb0ac.firebasestorage.app',
    measurementId: 'G-K9CNSD3RVY',
  );
}